
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.06
name: CGI-Capture
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  perl: 5.6.0
  IO::String: 1.07
  Storable: 2.11
abstract: Meticulously thorough capture and replaying of CGI calls
